- name: Add Filebeat Key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
  tags: debug

- name: Add the filebeat PPA
  apt_repository:
    repo: deb https://artifacts.elastic.co/beats/apt stable main
    state: present
  tags: debug
 
- name: Install filebeat
  apt:
    name: filebeat
    update_cache: yes
  tags: debug

- name: Enable filebeat service
  systemd:  
    name: filebeat
    enabled: yes 
  tags: debug

- name: Copy filebeat config file
  copy:
    src: /home/ansible/plays/suricata/roles/filebeat/files/filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  tags: debug

- name: Make sure the certificate directory exists
  file: path=/etc/pki/tls/certs state=directory
  tags: debug

- name: Copy logstash certificate
  copy:
    src: /home/ansible/plays/suricata/roles/filebeat/files/logstash-forwarder.crt
    dest: /etc/pki/tls/certs/logstash-forwarder.crt
    owner: root
    group: root
    mode: "u=r,g=r,o=r"
  tags: debug

- name: flush handlers to prevent start then restart
  meta: flush_handlers
  tags: debug

- name: Restart filebeat to get things a movin...
  service: 
    name: filebeat
    state: restarted
  tags: debug
