---
suricata_sniffing_interface: sniff
suricata_sniffing_interface_type: 1000M
suricata_rules_archive_url: http://rules.emergingthreats.net/open/suricata/emerging.rules.tar.gz
suricata_log_dir: /nsm/suricata/logs/
suricata_log_dir_certs: /nsm/suricata/logs/certs/
suricata_rules_dir: /etc/suricata/rules/
